queue_rules:
  - name: default
    queue_conditions:
      - "check-success=test / test"
    merge_conditions:
      - "check-success=test / test"
    batch_size: 1
merge_queue:
  max_parallel_checks: 1
pull_request_rules:
  - name: automatic merge for Scala Steward
    conditions:
      - author=tna-da-bot
      - "check-success=test / test"
      - or:
          - files=build.sbt
          - files~=^(!?project/)
    actions:
      review:
        type: APPROVE
        message: Automatically approving Scala Steward
      queue:
        name: default
